lib/rest2.js
Add add pool and explorer to currencies
=> add pool and explorer to currencies

lib/rest2.js
Refactor re used code
Unify responses to promises
Solve an issue with .wallets when a CB function was not send
=> Refactor callback options

doc/rest2.md, lib/rest2.js, test/lib/rest-2-integration.js
Add tradingTickerHist and fundingTickerHist
=> Tickers hist

package.json
bump a version + add ezequiel as contributor
=> bump a version + add ezequiel as contributor

doc/rest2.md, lib/rest2.js, test/lib/rest-2-integration.js
Add option for currency to walletsHistory
=>  Add option for currency to walletsHistory

package.json
Bump a version as to be able to use last changes
=> Bump a version

.babelrc, package.json
=> Fix: Move babel deps to dev, add babelrc

doc/rest2.md, lib/rest2.js, package.json
Add compatibility to option symbols with api v2
=> V2 compatibility

doc/rest2.md, lib/rest2.js, package.json
Add All option to funding trades
=> Funding trades

doc/rest2.md, lib/rest2.js
=> Add futures

lib/rest2.js, package.json
Add symbol option to currencies
=> Add symbol

doc/rest2.md, lib/rest2.js, package.json, test/lib/rest-2-integration.js
Add rest endpoint derivsPositionCollateralSet
Required for tests https://github.com/bitfinexcom/bfx-api-mock-srv/pull/21
=> Deriv pos col set

doc/rest2.md, lib/rest2.js, package.json, test/lib/rest-2-integration.js
Add liquidations (https://docs.bitfinex.com/v2/reference#rest-public-liquidations) to rest api.
Depends on following PRs: 
- https://github.com/bitfinexcom/bfx-api-mock-srv/pull/22
- https://github.com/bitfinexcom/bfx-api-node-models/pull/23
=> Liquidations

.github/PULL_REQUEST_TEMPLATE, CHANGELOG, README.md, docs/rest1.md, docs/rest2.md, lib/rest2.js, package.json
Updates documentation as per the new spec.
=> (feature) normalize docs, bump to 2.0.1

CHANGELOG, lib/rest2.js, package.json
My original pr included a circular dep bug since the utils module was also requiring the node-models repon. Even though I wasnt able to reproduce the error personally, Im sure this will fix the problem
None
None
=> Fix circular dep

CHANGELOG, README.md, package.json
=> 2.0.3 Fix missing docs commits

CHANGELOG, docs/rest2.md, lib/rest2.js, package.json
=> 2.0.5 Feature: Order Affiliate Codes

CHANGELOG, lib/rest2.js, package.json
Fixed wrong function called on submitFundingOffer.
This issue was created in '(feature) affCode support, bump to 2.0.5' commit 8dc554c417d5b98cf2559fc2401275e3997f3d5a
=> fixed submitFundingOffer

docs/rest2.md, lib/rest2.js
...
- [ Add method to cancel all active funding offers (https://docs.bitfinex.com/reference#rest-auth-cancel-all-funding-offers)]
=> Add method to cancel all funding offers

lib/rest2.js
Update account summary as to be compatible with v2
=> Update accountSummary endpoint

CHANGELOG, package.json, test/lib/rest-1-integration.js, test/lib/rest-2-integration.js, test/lib/rest-2-issue-80-argument-length.js, test/lib/rest-2-smoke-test.js
=> Fix: Concurrent tests 3.0.3

CHANGELOG, package.json, test/lib/rest-2-integration.js, test/lib/rest-2-unit.js
fixed broken tests for marketAveragePrice
none
none
marketAveragePrice function tests
=> fixed marketAveragePrice tests

.babelrc, CHANGELOG, lib/rest2.js, package.json
...
add _cust_ip to generateToken function
=> Add ip to token

package.json
=> forced deps

lib/rest2.js
- Added back Recurring AO endpoints removed in a previous commit : https://github.com/bitfinexcom/bfx-api-node-rest/commit/5f9264dcd377b9155071753778569600899254e3 
- Refactored method params to match other method params format 
=> - Added back Recurring AO endpoints removed in a previous commit 
